trigger:
  branches:
    include:
      - main  # Trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python3 -m pip install --upgrade google-auth google-cloud-storage
  displayName: 'Install Google Cloud Storage SDK'

- script: |
    echo ${GCP_CREDENTIALS} > gcp-key.json
    gcloud auth activate-service-account --key-file=gcp-key.json
    gsutil cp index.html gs://researchsite1/
  env:
    GCP_CREDENTIALS: $(GCP_CREDENTIALS)
  displayName: 'Deploy to GCS'

